### ISSUE TITLE
How do I use an https node for --apiAddress?

### ISSUE THREAD

**Issue by Tsangares** [iotaledger/rpchub#207]
This is not an issue with the code it is an issue with me.
There is not a lot of tutorials, so I do not know where else to ask this.
I want to connect to the IRI node using HTTPS, but when I do it, I receive errors.

How do I connect to an IRI node that only supports https?

Does it have anything to do with `--authMode`?

**Comment by th0br0** [comment]
Hey @tsangares, 
Thanks for trying out the Hub!
At the moment, the hub only has support for http as IRI only supports http natively and http doesn't add that much over http in the context of the current IRI REST API.
HTTPS support would only make sense in combination with certificate pinning etc. we've got it on our roadmap but our efforts are currently focused elsewhere. I can update you once we've added it though!

**Comment by Tsangares** [comment]
Cool thanks; I have been testing rpchub without hosting my own iri.
Knowing this I will just put the effort in to get my own.

THANK YOU! Good job on all the work you do!

**Comment by th0br0** [comment]
Sure - if you're just testing you could also proxy Https to http via mitmproxy or similar

**Comment by Tsangares** [comment]
whoa  thanks for the tip

**Comment by Tsangares** [comment]
My solution was to install and use `stunnel`

My `/etc/stunnel/stunnel.conf`:

    [remote]                                                                                                                                                                 
    client = yes                                                                                                                                                             
    accept = 1234                                                                                                                                                            
    connect= node.iota.moe:443   

Then in my `/etc/hosts` I had to add the line:

    127.0.0.1 node.iota.moe

Because when `stunnel` proxies `localhost:443` to `node.iota.moe:443` it sends in the REST header with `Host: localhost` but we want it to be `Host: node.iota.moe` or else the webserver hosting the iri node stops the connect.

Now I just tell my rpchub to connect to `node.iota.moe:1234` and `stunnel` handles the https.
