### ISSUE TITLE
grpc stream for updated balance?

### ISSUE THREAD

**Issue by Tsangares** [iotaledger/rpchub#210]
### Description
Currently I am using a timer to check rpchub for if a balance is updated. But grpc supports bi-directional streams.
Can I open a stream and wait for rpchub to tell ME when the balance is updated?

### Motivation
Handling timers is a pain I would rather have a callback and a timeout.

### Requirements
 - stream in the proto files

### Open Questions (optional)
Is this already implemented in some way?

### Am I planning to do it myself with a PR?
no

**Comment by th0br0** [comment]
Hey, 
there's currently no internal eventing system in RPCHub which would be required to provide such streaming updates. Most of our current users are happy with the poll-based interface, so adding such a streaming interface is not of a high priority for us.

We're open to PRs though of course ;)
