### ISSUE TITLE
Incorrect and Dangerous Behavior When Using GetDepositAddress and UserWithdraw too fast and in parallel

### ISSUE THREAD

**Issue by Tsangares** [iotaledger/rpchub#213]
### Bug description
For testing purposes I have one user_account with 10KIOTA and I want to send 1KIOTA to 10 other user_accounts.
Using node.js for the grpc client, I can `GetDepositAddress` and `UserWithdraw` from all user_account in parallel.

Let `accounts` be a list of valid rpb hub `user_account`, and `main_user` be the username with a balance of 10KIOTA. 
Let `transfer(from,to,amount)` be a wrapper for the `GetDepositAddress` and `UserWithdraw` that calls `GetDepositAddress({userId: username},callback)` before calling `UserWithdraw({userId: main_user, payoutAddress: address, amount: amount, validateChecksum: true}, callback)`.

The following code:

    accounts.forEach(user=>{
        transfer(main_user, user, 1000)
    })

Instead of sending 1KIOTA to each user, sends 10KIOTA to the last user in the user list; defiantly not what I was expecting. I thought it was an issue on my side until this was my solution:

    i=0
    accounts.forEach(user=>{
        i+=1
        setTimeout(()=> transfer(main_user, user, 1000), 500*i)
    })

Which now delays the execution of GetDepositAddress by .5 second or 500 mili sec.

I can go as low at 100 mili seccond for everything to work. At 10 milisecond delay, very strage and unpredictable address behavior occurs. At >5 milisecconds all money goes to the last address.

### Hardware Spec
Arch Linux Mac Book Pro

### Expected behaviour
Money should be distributed across all users in `accounts`

### Actual behavior
All transactions go to the last user in the list of `accounts`, because GetDepositAddress when ran too fast keeps returning the same value.

I am busy now but I can possibly write more errors and testable code later. I just thought I should post this because, even though I found a reasonable solution this seems like it could be an obscure bug worth fixing for future users.

**Comment by Tsangares** [comment]
Here is all the code I was using: https://raw.githubusercontent.com/Tsangares/rpchub_testcase/master/test.js

On another note, do you happen to have the endpoint to some http iri nodes?
https://iota.dance/ is running thin on them, there is only 2 now.
I tried using `stunnel` as a http->https proxy but it was shortlived.

**Comment by th0br0** [comment]
Hey @Tsangares , could you have a look at the latest master and see if the problem persists?

The issue at hand might be related to your local system - could you provide more info on that?

**Comment by Tsangares** [comment]
I will rebuild the master. I was thinking that this could be a grpc error actually. I dont know how the protocol works but I am stressing it when I run this function, if I am only using one process to handle 10 requests that occur all at once, hm....

What would you like to know about my system specifically? 
nodejs 10.11.0

**Comment by th0br0** [comment]
Ah, I was interested in your operating system / GCC or Clang version.
`std::random_device` has some really unintuitive behaviour in some situations.

**Comment by Tsangares** [comment]
Clang version is 7.0.0
gcc (GCC) 8.2.1 20180831

**Comment by Tsangares** [comment]
Confirmed, I still have this issue.

**Comment by th0br0** [comment]
Hey @Tsangares , I'm still having trouble reproducing your issue. I have tried various configurations of your testcase adjusted for functionality without any effect. 

- Which database are you using? MariaDB or SQLite3?
- Are you sure this is not a race condition inside your application?
- Can you provide me with the complete Hub startup parameters? 

> Instead of sending 1KIOTA to each user, sends 10KIOTA to the last user in the user list
Could you be misinterpreting the second sweep (that happens after the initial batch of withdrawals) that moves all funds into a single address?

**Comment by th0br0** [comment]
Hey @Tsangares any follow up here? I'll close over the coming days otherwise

**Comment by Tsangares** [comment]
I am using mariaDB.

**Are you sure this is not a race condition inside your application?**
I want to say yes, but I feel as though its hard to be certain about this. 

**Can you provide me with the complete Hub startup parameters?**
```./rpchub/bazel-bin/hub/hub --salt $SALT --apiAddress $NODE --db iota --dbUser $USER --dbPassword $PASS --monitorInterval 5000 --attachmentInterval 30000 --sweepInterval 5000 --minWeightMagnitude 14 --maxNumAddressesForGetBalances 10 --powMode remote```

**Comment by th0br0** [comment]
A DB dump would be good if possible as well. I'll try to write up a repro case again tomorrow.

**Comment by Tsangares** [comment]
Did you use nodejs & async requests when you tried to reproduce it?

**Comment by th0br0** [comment]
Yeah, pretty much used yours - slightly adjusted

**Comment by Tsangares** [comment]
I just polished up the test code I gave you and reran it and every thing is fine. I am going to assume its somewhere within my own code. Sorry for all the distraction.
