### ISSUE TITLE
Iota hub don't send 0 iota

### ISSUE THREAD

**Issue by iauglov** [iotaledger/rpchub#223]
I need validate address how i can do it?
I try send zero to address and check result, may be iota hub have method for validate address, and we need check validate that address not our users

**Comment by iauglov** [comment]
I want it for validate iota address

**Comment by th0br0** [comment]
I don't follow. There's no need to validate an address via the Hub. 
The various client libraries offer you the ability to validate the checksum of an address (if it's 90 trytes long).

Other than that, any 81 tryte string is a valid address in theory

**Comment by iauglov** [comment]
ok thanks
