### ISSUE TITLE
Hub build fails on Bazel 0.21

### ISSUE THREAD

**Issue by xkf4806** [iotaledger/rpchub#227]
### Bug description
when I build rpchub, error occurs like picture.This looks like it could be an issue with the Bazel BUILD file
### Hardware Spec
environment： CentOS7_x64
![image](https://user-images.githubusercontent.com/7620676/50892116-bc37ac00-1438-11e9-90b1-6739c950e2f3.png)

**Comment by th0br0** [comment]
Hey @xkf4806 - a hot fix is to simply supply `--incompatible_package_name_is_a_function=false` when building.  I'll look into a proper fix now.

As you're building on CentOS: please make sure that you've got devtoolset-8 or devtoolset-7 installed and have setup your CC/CXX env vars properly! (after you've done that, be sure to run a `bazel clean`)
