### ISSUE TITLE
hub service does not acquire deposit event correctly.

### ISSUE THREAD

**Issue by xkf4806** [iotaledger/rpchub#229]
### Bug description
when deposit some iota tokens to an address, the transaction has been confirmed in the devnet tangle explorer,but hub can not retrieve the record correctly.

### Hardware Spec
CentOS7 VPS

### Steps To Reproduce
transaction bundles are:
1.
LLQBHRILGZXVGWPKCOOHE9QJHV9NF9VVYZLWDNNOSQDLFBDDDSFHJAINT9ETGYKRRW9COUTKEYBFCJIVD
2. IHSREIQEYBRIBSKCUVQHQAJBGSUXYHNFDRPOLZZAPNROKZKIEGFFIL9MFJE9TFEKBZZOZCEYWKVVXBUHC
3. FGXTIDTHJWYQCWEAZUVDLXKXGHWLDGRFJZJLLQ9LQFUCOTPTSTYRDGEEBUKJGNKKYWGJVJY9FTBXVZNJD

### Expected behaviour
the hub database should insert the deposit record.

### Actual behavior
none

### Errors
hub service went wrong, and error log like this:
![image](https://user-images.githubusercontent.com/7620676/51835136-72572d00-2337-11e9-80cc-6218ad13c26b.png)

**Comment by th0br0** [comment]
Hi @xkf4806  - thanks for filing this.

I've got a hunch as to what might be causing this. Could you check if the *tails* of the bundles depositing into `GXQSTFDKMY...` are part of your DB already? `SELECT tail_hash, user_address FROM user_address_balance WHERE tail_hash IN ("C9PUHZJSLVJKIDMKKQLLHBY9RURQKAKWBELEHMSQPFGNQUEGEALXDQJBFGZDSSZ9MSMVKDBEEDTVA9999", "SBMNFJZAAPSWCIBIB9BHJHQOPTIJVLXUSKENHY9HQ9DXVXQYMPKWLDHUMJNGXHNZZWNRWQNKSAUP99999", "ADRQROQJFLUNYUYOUSUXEQVJVEZWFVJXRMYLLZRPFAGTIOMGJSQKZBVFQGSFNZMOEBLUDLNTRKNHA9999");`

Could you also provide more information about your setup? Given that this appears to be devnet, are you able to share your database with me?

**Comment by xkf4806** [comment]
hi, I've gone off work, I'll do that tomorrow morning.

**Comment by th0br0** [comment]
After following up on this via Discord, this appears to be a case of the IRI node not being fully synced when the Address Service is running.

This is, essentially, working as intended. But I'll add a node health check to the balance checker as well.
