### ISSUE TITLE
Feature Request: Read message of a tx

### ISSUE THREAD

**Issue by omoku** [iotaledger/rpchub#237]
### Description
The Hub should not only be able to read the value of a transaction, but also the message that can be part of a transaction.

### Motivation
The option to read the message of a transaction would allow exchanges to execute sell orders more directly and lead to the easier implementation of open API of the own services. Automation level would increase with this feature when information can be sent and read directly and automatically. It could also lead to new possibilities regarding KYC in the process of onboarding new users, especially when used together with MAM. It could be significant beyond the scope of exchanges.

### Requirements
- The Hub should be able to read the message of a transaction

### Open Questions (optional)
-

### Am I planning to do it myself with a PR?
Not planned, but we could help with the implementation.

**Comment by tsvisabo** [comment]
Thanks @omoku  for that request,
However, not sure to understand your intention,
How do you mean that the Hub should be able to read a message?
Should the Hub be able to "understand" the messages too?
Should messages contain instructions?
If so, what kind of instructions?

**Comment by omoku** [comment]
Thanks for your reply and sorry for the unclear term. I was talking about the „message“ that you can write, send and read together with IOTA transactions, for example in the Trinity Wallet. Messages can contain whatever the user entered.

**Comment by tsvisabo** [comment]
Of course, but the question remains, what should be done with the transaction's message?
with value, user ask for an address to deposit to, hub monitor that address for balance changes and if anything is found it will credit the user associated with that address with that balance, user then can withdraw the value,
would you like to do something that is analogous to that with the transaction's message?
i imagine that together with withdraw user will be able to *read* the message using an additional command?
that will also require storing those messages in the _user_account_ table, that will dramatically increase the hub db size IMO,
When should a message be discarded from user's account?
overall, very much possible

**Comment by omoku** [comment]
From our perspective, we don‘t see a significant use case for something like that. The intention of the request was just that the exchange / service is able 

- to read the message from an incoming transactionand then 
- use that information for further processing the transaction/order and 
- trigger further action based on the individual use case.

**Comment by omoku** [comment]
The affected method would be „balance subscription“. I hope it‘s clearer now what we would like to achieve.

**Comment by tsvisabo** [comment]
That's clear enough and quite not hard to do, should be configurable however because i guess most users wouldn't like to store messages,
btw, who's "we"? :)

**Comment by omoku** [comment]
That‘s great! Implementing it as a configurable feature sounds reasonable. „We“ is our team from omoku.io :)
