### ISSUE TITLE
Hub build fails on Bazel 0.25

### ISSUE THREAD

**Issue by garfieldevop** [iotaledger/rpchub#242]
Bug description
when I build rpchub, many error occurs like this:
---------------------------------------
![Captura de pantalla de 2019-05-15 21-43-19](https://user-images.githubusercontent.com/44278910/57820382-93168780-775a-11e9-963b-90333da846bb.png)

-------------------------------------

This looks like it could be an issue with the Bazel BUILD file

Hardware Spec
environment： Ubuntu 18.04

**Comment by tsvisabo** [comment]
Thanks, need to update the toolchains to work with Bazel-0.25, it will take a bit because doing so fails our CI build because it runs on 0.17, so we need to upgrade first.
In any case, when #243 is merged

**Comment by tsvisabo** [comment]
@garfieldevop , can you check latest?

**Comment by tsvisabo** [comment]
not anymore
