### ISSUE TITLE
Provide a `RecoverFunds` API call

### ISSUE THREAD

**Issue by fijter** [iotaledger/rpchub#257]
### Description
The `RecoverFunds` API call allows you to move all funds from an address that has already been spent from to another, clean address. 

### Motivation
The current way of recovering funds stuck in an address that has already been sweeped is cumbersome and hard, it requires an external script creating a custom bundle outside of the scope of Hub. It would be great if this process can be simplified with an easy to use API call so it's less error prone and easier to work with.

### Requirements

 - `RecoverFunds` should get an address as input and a new address as output
 - It should make sure all funds in the given address are transfered to the new address
 - It should be well documented that this is a last-resort API and should only be used for recovery after address re-use.

### Open Questions

 - Maybe it's even better to provide an address only (optionally a user id as well if it can't easily be derived from the address) where the recover method automatically generates a new deposit address for the user and transfers the funds there. 

### Am I planning to do it myself with a PR?
No.

**Comment by tsvisabo** [comment]
fixed by #260
